# -------------------------
# Build Stage
# -------------------------
    FROM alpine:latest AS build

    LABEL AUTHOR="AYUSH-GUPTA-Martyr112"
    
    # Set the working directory
    WORKDIR /app
    
    # Copy all app files into container
    COPY . /app/
    
    # Set environment variables (will be used at build time)
    ARG VITE_API_URL
    ARG VITE_BUCKET_URL
    ARG VITE_AESKEY
    ARG VITE_FRONTEND_URL
    ARG VITE_API_URLT
    ARG VITE_EDITOR_API_KEY
    ARG VITE_PAYMENT_API_URL
    ARG VITE_ADMIN_REFERRAL_TOKEN
    
    # Install Node.js and npm, then build app
    RUN apk add --no-cache nodejs npm \
        && npm install --force \
        && npm run build \
        && rm -rf /root/.npm
    
    
    # -------------------------
    # Production Stage
    # -------------------------
    FROM alpine:latest
    
    # Set working directory
    WORKDIR /app
    
    # Copy built files from build stage
    COPY --from=build /app/dist /app/dist
    COPY server_files/ /app/
    
    # Install runtime dependencies
    RUN apk add --no-cache nodejs npm nginx apache2-utils \
        && npm install -g serve \
        && mkdir /logs \
        && cp -f default-prod.conf /etc/nginx/http.d/default.conf \
        && chmod +x script.sh \
        && rm -rf /root/.npm default*
    
    # Expose port (you might already have this)
    EXPOSE 80
    
    # Start the app
    CMD ["./script.sh"]
    