server {
    listen 80 default_server;
    listen [::]:80 default_server;

    access_log /logs/nginx_acces.log;
    error_log /logs/nginx_error.log;

    location / {
        # auth_basic "Administrator's Area";
        # auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:3000;
    }
}