server {
    listen 80 default_server;
    listen [::]:80 default_server;

    access_log /logs/nginx_acces.log;
    error_log /logs/nginx_error.log;

    location / {
        proxy_pass http://localhost:3000;
    }
}