---
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # Required for git checkout

jobs:
  Build_Push_Deploy_Docker_Image: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        id: AWS_Login_Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1.6.0

      - name: Deploy to Test Server
        if: |
            hashFiles('**/Dockerfile', '**/dockerfile') &&
            github.ref != 'refs/heads/main' 
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: | 
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPO }}:test
          build-args: |
            VITE_API_URL=${{ vars.VITE_TEST_API_URL }}
            VITE_BUCKET_URL=${{ vars.VITE_BUCKET_URL }}
            VITE_AESKEY=${{ secrets.VITE_AESKEY }}
            VITE_FRONTEND_URL=${{ vars.VITE_TEST_FRONTEND_URL }}
    
      - name: Deploy to Production Server
        if: | 
            hashFiles('**/Dockerfile', '**/dockerfile') &&
            github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: | 
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPO }}:latest
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPO }}:${{ github.run_number }}
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_BUCKET_URL=${{ vars.VITE_BUCKET_URL }}
            VITE_AESKEY=${{ secrets.VITE_AESKEY }}
            VITE_FRONTEND_URL=${{ vars.VITE_FRONTEND_URL }}

  # name: Use Private Action
  # on:
  #   pull_request:
  #     branches:
  #       - main
  
  # permissions:
  #   contents: read # Required for git checkout
  #   packages: write
  
  # jobs:
  #   run:
  #     steps:
  #       uses: Official-EngineerHUB/github-shared-actions@main
  #       secrets:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       env:
  #         ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  #         ECR_REPO: ${{ vars.ECR_REPO }}
  #         ECR_REGION: ${{ vars.ECR_REGION }}
  #         VITE_API_URL=${{ vars.VITE_API_URL }}
  #         VITE_BUCKET_URL=${{ vars.VITE_BUCKET_URL }}
  #         VITE_AESKEY=${{ vars.VITE_AESKEY }}