name: Validate Docker Build

on:
  push:
    branches:
      - main
      - testing

permissions:
  contents: read

jobs:
  Validate_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Validate Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Adjust to match the appropriate Dockerfile for the environment
          push: false # Only validate, no push
          tags: temp-build:latest
          build-args: |
            VITE_API_URL=${{ vars.VITE_TEST_API_URL }}
            VITE_BUCKET_URL=${{ vars.VITE_BUCKET_URL }}
            VITE_API_URLT=${{ vars.VITE_TEST_API_URL }}
            VITE_AESKEY=${{ secrets.VITE_AESKEY }}
            VITE_FRONTEND_URL=${{ vars.VITE_TEST_FRONTEND_URL }}
            VITE_EDITOR_API_KEY=${{ secrets.VITE_EDITOR_API_KEY }}
            TEST_SERVER_USERNAME=${{ secrets.TEST_SERVER_USERNAME }}
            TEST_SERVER_PASSWORD=${{ secrets.TEST_SERVER_PASSWORD }}
            VITE_PAYMENT_API_URL=${{ vars.VITE_PAYMENT_API_URL_TESTING }}
            VITE_ADMIN_REFERRAL_TOKEN=${{ vars.VITE_ADMIN_REFERRAL_TOKEN }}
